# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Marion
tagline:          "hi, i'm marion"
description:      'Just a place for me to organize my thoughts, write, and code. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://www.heymarion.me
baseurl:          /

author:
  name:           'Marion Xu'
  url:            ''

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/heymarion
