# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Marion
tagline:          'everything and anything'
description:      "just a place for me to organize my thoughts."
url:              http://www.heymarion.me
baseurl:          /

author:
  name:           'Marion Xu'
  url:            ''
  email:	      marion@heymarion.me

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/heymarion
